blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blogapp.sitemaps import PostSitemap



sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),

]

blog/blogapp/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blogapp'

urlpatterns = [
 # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

    ]

blog/blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')




class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager() #Теги

    objects = models.Manager()  # Менеджер по умолчанию.
    published = PublishedManager()  # Новый менеджер.


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogapp:post_detail', args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/blogapp/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/blogapp/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blogapp/post/list.html'
#

def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
    # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    return render(request,'blogapp/post/list.html', {'page': page, 'posts': posts, 'tag':tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',publish__year=year,
                                publish__month=month,publish__day=day)
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
    # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
    # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
    # Привязываем комментарий к текущей статье.
            new_comment.post = post
    # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Формирование списка похожих статей.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blogapp/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})




def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id,status='published')
    sent = False
    if request.method == 'POST':
    # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию.
            cd = form.cleaned_data
            # Отправка электронной почты.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'qweqweqweadmin@blogapp.su', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blogapp/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', 'body')
        search_query = SearchQuery(query)
        results = Post.objects.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).filter(search=search_query).order_by('-rank')
    return render(request, 'blogapp/post/search.html', {'form': form,'query': query,'results': results})

blog/blogapp/templates/blogapp/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'css/blogapp.css' %}" rel="stylesheet">
</head>
<body>
 <div id="content">
    {% block content %}{% endblock %}
 </div>
 <div id="sidebar">
  <h2>Мой Блог</h2>
      <p>Это мой блог. Я написал {% total_posts %} постов.</p>
  <h3>Latest posts</h3>
  {% show_latest_posts 3 %}

  <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
       {% for post in most_commented_posts %}
       <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
     {% endfor %}
    </ul>
     <p><a href="{% url "blog:post_feed" %}">RSS</a></p>
 </div>
</body>
</html>

blog/blogapp/templates/blogapp/post/detail.html
{% extends "blogapp/base.html" %}
{% loadblog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
 {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
 {% endwith %}
    <h1>{{ post.title }}</h1>
    <p class="date">Пост {{ post.publish }} написан автором {{ post.author }}</p>
 {{ post.body|markdown }}
    <p>
    <a href="{% url 'blogapp:post_share' post.id %}">Поделиться статьей</a>
   </p>

    <h2>Похожие статьи</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Пока что нету похожих статей.
    {% endfor %}


 {% for comment in comments %}
   <div class="comment">
   <p class="info">Комментарий {{ forloop.counter }} от {{ comment.name }}{{ comment.created }}</p>
      {{ comment.body|linebreaks }}
  </div>
 {% empty %}
  <p>Пока что нет комментариев.</p>
 {% endfor %}

 {% if new_comment %}
      <h2>Your comment has been added.</h2>
 {% else %}
      <h2>Add a new comment</h2>
      <form action="." method="post">
           {{ comment_form.as_p }}
           {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
      </form>
 {% endif %}

{% endblock %}

blog/blogapp/templates/blogapp/post/latest_posts.html
<!DOCTYPE html>

<ul>
 {% for post in latest_posts %}
 <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
 {% endfor %}
</ul>

blog/blogapp/templates/blogapp/post/list.html
{% extends "blogapp/base.html" %}
{% load blog_tags %}
{% block title %}Мой блог{% endblock %}
{% block content %}
 <h1>Мой блог</h1>
    {% for post in posts %}
     <h2>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
     </h2>
        <p class="tags">Теги:
            {% for tag in post.tags.all %}
                <a href="{% url 'blogapp:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}</p>
        <p class="date">Опубликовано {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/blogapp/templates/blogapp/post/search.html
{% extends "blogapp/base.html" %}
{% block title %}Поиск{% endblock %}
{% block content %}
{% if query %}
<h1>Пост содержит "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
Found {{ total_results }} result {{ total_results|pluralize }}
{% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>По вашему запросу ничего не найдено.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search' %}">Искать снова</a></p>
{% else %}
<h1>Поиск записей</h1>
<form action="." method="get">
{{ form.as_p }}
<input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

blog/blogapp/templates/blogapp/post/share.html
{% extends "blogapp/base.html" %}
{% block title %}Поделиться публикацией{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Поделиться "{{ post.title }}" по e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/blogapp/templates/pagination.html
<!DOCTYPE html>
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Предыдущая</a>
        {% endif %}
        <span class="current">
            {{ page.number }} страница из {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Следующая</a>
        {% endif %}
    </span>
</div>